server:
  port: 8080
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: databasename
  username: root
  password: 11111111
  charset: utf8mb4
  maxOpenConns: 100
  maxIdleConns: 20
redis:
  host: 127.0.0.1
  port: 6379
  MaxIdle:  3
  MaxActive:   8
kafka:
  host: 127.0.0.1
  port: 9092
tail:
  filename: ./my.log
etcd:
  host: 127.0.0.1,127.0.0.1,127.0.0.1
  port: 12379,22379,32379
