server:
  port: 8080
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: ginweb
  username: root
  password: Fjy13819372207
  charset: utf8mb4
  maxOpenConns: 100
  maxIdleConns: 20
redis:
  host: 127.0.0.1
  port: 6379
  MaxIdle:  3
  MaxActive:   8
